name: 'datawarehouse'
version: '0.1'
profile: 'datawarehouse'
source-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  materialized: table
  test.sql
